import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { privacyPolicy } from "./ReservationJoin";
const PrivacyConsentModal = ({ consents, onChange, onAllConsent, isAllChecked, isAgreed, onClose, onSubmit, checkboxesRefs, }) => {
    return (_jsx("div", { className: "fixed inset-0 bg-gray-600 bg-opacity-50 flex justify-center items-center z-50 px-4", children: _jsxs("div", { className: "bg-white p-6 rounded-lg w-full sm:w-[700px] max-h-[90vh] overflow-y-auto", children: [_jsx("h1", { className: "text-2xl font-semibold mb-4", children: "\uAC1C\uC778\uC815\uBCF4 \uCC98\uB9AC\uBC29\uCE68" }), _jsx("div", { className: "flex justify-end mb-4", children: _jsx("button", { onClick: onAllConsent, className: "text-sm text-blue-600 underline hover:text-blue-800", children: isAllChecked ? "전체 동의 해제" : "전체 동의" }) }), _jsx("div", { className: "space-y-6", children: privacyPolicy.map((section, index) => (_jsxs("div", { children: [_jsx("h2", { className: "text-xl font-bold", children: section.title }), _jsx("div", { className: "mt-2 max-h-48 overflow-y-auto pr-2 border rounded p-2 bg-gray-50", children: section.content.map((paragraph, i) => (_jsx("p", { className: "text-gray-700 mb-2 text-sm", children: paragraph }, i))) }), _jsx("div", { className: "mt-4", children: _jsxs("label", { className: "flex items-center space-x-2", children: [_jsx("input", { ref: (el) => {
                                                checkboxesRefs.current[index] = el;
                                            }, type: "checkbox", checked: consents[section.title] || false, onChange: (e) => onChange(e, section.title, index), className: "w-5 h-5" }), _jsx("span", { className: "text-gray-700 text-sm", children: "\uC774 \uD56D\uBAA9\uC5D0 \uB3D9\uC758\uD569\uB2C8\uB2E4." })] }) })] }, index))) }), _jsxs("div", { className: "flex justify-between mt-6", children: [_jsx("button", { onClick: onClose, className: "px-6 py-2 bg-gray-500 text-white rounded-md hover:bg-gray-600", children: "\uB2EB\uAE30" }), _jsx("button", { disabled: !isAgreed, onClick: onSubmit, className: `px-6 py-2 text-white rounded-md ${isAgreed
                                ? "bg-green-500 hover:bg-green-600"
                                : "bg-gray-400 cursor-not-allowed"}`, children: "\uB3D9\uC758\uD558\uACE0 \uC81C\uCD9C\uD558\uAE30" })] })] }) }));
};
export default PrivacyConsentModal;
